### ISSUE TITLE
How to get values of a metric between given time window

### ISSUE THREAD

**Issue by Dentrax** [calyptia/cmetrics#126]
I have the following variables:

```
struct cmt_counter *foo;
struct cmt_metric *bar
or histrogram
```

I want to get the values and traverse over the _foo_ or _bar_ in the last X seconds or between given time range.

For example;

1. traverse cmt_counter or cmt_metric values
2. if timestamp of value >= now()
3. total_sum += value

How can I achieve this using cmetrics?

**Comment by Dentrax** [comment]
Thanks, so does it make sense to implement something like:?

```
struct cmt_counter_with_timestamp {
    uint64_t timestamp;
    struct cmt_counter *foo;
};

struct cmt_metric_timeseries {
    struct cmt_counter_with_timestamp *counter_buckets;
};
```

What I want is to store a time info after each _set, inc, dec_ etc. operations. By doing so I can traverse the array and compare the timestamp. 

My concern here is would it be lead to any memory leaks by keep continuously allocating `cmt_counter_with_timestamp` struct? Should I implement some retention stuff such as _free()_ all counters that older than i.e., `1m`. I bit confused and lost here.

**Comment by edsiper** [comment]
every single metric has its own timestamp, the question is about how you want to handle that by using labels. 

Sorry but I cannot assist at the moment in the design of this kind of functionality. but what is the use case ?

**Comment by Dentrax** [comment]
My use case is to achieve similar functionality of [rolling numbers](https://github.com/afex/hystrix-go/blob/master/hystrix/rolling/rolling.go) using `cmetrics` library. Since C does not have _maps_, I'm a bit struggling about implementing same logic by combining this library + dynamic allocation and pointer stuff.

**Comment by edsiper** [comment]
At the moment this is not in the scope of CMetrics project, for hence I am closing the ticket.
