### ISSUE TITLE
prometheus decoder: add support for Histograms and Summaries

### ISSUE THREAD

**Issue by edsiper** [calyptia/cmetrics#84]
Through PR #83 CMetrics just got support for Histograms metrics type. 

For the context of the decoder, the parser needs to process histograms, create the list of buckets and initialize the histogram with default values for the buckets, sum, and count. An example can be found here:

- https://github.com/calyptia/cmetrics/blob/master/tests/histogram.c#L125-L149

**Comment by edsiper** [comment]
FYI: In #87 I've added Summaries support.

The API is pretty similar to Histograms but just a bit simpler since we don't do data observation. Usage examples:

- https://github.com/calyptia/cmetrics/blob/master/tests/summary.c#L55-L76

**Comment by tarruda** [comment]
This can be closed @edsiper

**Comment by edsiper** [comment]
thanks
