### ISSUE TITLE
aarch64 builds

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cmetrics#96]
### Description

Generate artifacts for aarch64 and store them for unstable and tagged releases.
Additionally run tests on PR(s) for aarch64.

This can be achieved with a base dockerfile with aarch64 emulation and use it as a build
container, copy the artifacts or via a run-on-arch-action.

**Comment by edsiper** [comment]
do we still need this ?

**Comment by niedbalski** [comment]
We already have aarch64 builds @edsiper, so closing
